# Generated by Django 4.2.3 on 2023-07-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GospelNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_title', models.CharField(max_length=30, unique=True)),
                ('passage', models.CharField(blank=True, max_length=30)),
                ('specific_title', models.CharField(blank=True, max_length=15)),
                ('url', models.CharField(max_length=15)),
                ('video_upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_question', models.TextField()),
                ('second_question', models.TextField()),
                ('third_question', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('gospel_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.gospelnote')),
            ],
        ),
    ]
